[build]
publish = "build"
command = "npm run build"

[[redirects]]
from = "/v1/*"
to = "https://api.kakaobrain.com/:splat"
status = 200
force = true

from = "/data/*"
to = "https://api.openweathermap.org"
status = 200
force = true