[build]
publish = "build"
command = "npm run build"

[[redirects]]
from = "/api/*"
to = "https://api.kakaobrain.com/:splat"
status = 200
force = true

from = "/api/*"
to = "https://api.openweathermap.org"
status = 200
force = true