[build]
publish = "build"
command = "npm run build"

[[redirects]]
from = "/api/kakao/*"
to = "https://api.kakaobrain.com/:splat"
status = 200
force = true

[[redirects]]
from = "/api/weather/*"
to = "https://api.openweathermap.org/:splat"
status = 200
force = true
